name: Feature Branch - Docker Build

on:
  push:

permissions:
  packages: write

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Prepare Image tag name
        run: |
          # Extracting the substring after
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          # Converting to lower case and replace / with -
          BRANCH_NAME_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's|/|-|g')

          # creating new enironment variable
          echo "TAG_NAME=$BRANCH_NAME_LOWER" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }}
